### ISSUE TITLE
ReactServerComponentError

### ISSUE THREAD

**Issue by SSardorf** [resendlabs/resend-node#221]
I just upgraded to the new version of Nextjs (13.5.1) and am now getting the following error when trying to use Resend.

```
ReactServerComponentsError:

You're importing a component that imports react-dom/server. To fix it, render or return the content directly as a Server Component instead for perf and security.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

The error was caused by importing 'resend/build/src/index.js' in './lib/auth.tsx'.
```

**Comment by bukinoshita** [comment]
which version are you using?

**Comment by thibaultleouay** [comment]
I also have the issue 

Here's my code 
 https://github.com/openstatusHQ/openstatus/pull/326/files
When building it on vercel I have this issue 

![image](https://github.com/resendlabs/resend-node/assets/13894054/08c15f0f-bed8-4d7f-b613-0620b8611164)

**Comment by sethtjf** [comment]
I'm seeing the same error as well

**Comment by Dentling** [comment]
I had the same issue and for me the problem was that I was using `import { Tailwind } from "@react-email/tailwind"` instead of `import { Tailwind } from "@react-email/components"`

Since the component has to be a serverComponent, but the Tailwind-Component requiring some client-side stuff, I had that error.

idk maybe this helps.

Versions I use:

```
next: 13.5.3
resend: 1.1.0
@react-email/components: 0.0.7
@react-email/tailwind: 0.0.9
```


although I can remove `@react-email/tailwind` now 😃

**Comment by mr7r25** [comment]
same error

**Comment by herkulano** [comment]
> which version are you using?

@bukinoshita  v1.1.0 and have the same issue

**Comment by YourAverageTechBro** [comment]
I am seeing this error even on resend v2.1.0

**Comment by thiagobrito** [comment]
I still have the same issue in version 3.1.0. Should I open another issue?
